name: mapify
description: Package for converting objects to similar objects inline with clean architecture
version: 1.0.0
environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  test: 1.3.4
  analysis_options: any
