name: mapify
description: Package for converting objects to similar objects inline with clean architecture
version: 0.1.0
environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  analysis_options: any
  test: 1.3.4
