name: mapify_generator
homepage: https://github.com/LennardDeurman/mapify
description: Generator methods for mapify package
version: 0.1.5

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  build: ^2.3.1
  source_gen: ^1.2.6
  dart_style: ^2.2.4
  mapify: ^0.1.0
  analyzer: ^5.2.0

dev_dependencies:
  build_test:
  build_runner:
  test: ^1.0.0
