name: mapify_generator
description: Generator methods for mapify package
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  build:
  source_gen: ^1.2.6
  dart_style: ^2.2.4
  mapify:
    path: ../mapify/

dev_dependencies:
  build_test:
  build_runner:
  test: ^1.0.0
